# Dataset y tabla para almacenamiento de eventos
# BigQuery es ideal para analytics sobre eventos de seguridad

resource "google_bigquery_dataset" "events" {
  dataset_id = "security_events_${var.environment}"
  location   = var.location

  # Descripción para documentación en la consola
  description = "Security events processed by the CSE pipeline"

  # Labels para organización y billing
  labels = {
    environment = var.environment
    managed_by  = "terraform"
  }

  # Retención de datos: los eventos viejos se borran automáticamente
  # 90 días para dev, más para prod (se configura por ambiente)
  default_table_expiration_ms = var.table_expiration_days * 24 * 60 * 60 * 1000
}

# Tabla principal de eventos
# Schema basado en nuestro SecurityEvent type
resource "google_bigquery_table" "events" {
  dataset_id = google_bigquery_dataset.events.dataset_id
  table_id   = "events"

  description = "Normalized security events"

  # Particionado por día de ingesta para queries eficientes
  time_partitioning {
    type  = "DAY"
    field = "ingested_at"

    # Expiración de particiones viejas
    expiration_ms = var.table_expiration_days * 24 * 60 * 60 * 1000
  }

  # Clustering para queries comunes (por tipo de evento, severidad)
  clustering = ["event_type", "event_severity"]

  # Schema de la tabla
  # Tip: si cambias el schema, BigQuery permite agregar campos pero no quitarlos
  schema = jsonencode([
    {
      name = "id"
      type = "STRING"
      mode = "REQUIRED"
    },
    {
      name = "timestamp"
      type = "TIMESTAMP"
      mode = "REQUIRED"
    },
    {
      name = "ingested_at"
      type = "TIMESTAMP"
      mode = "REQUIRED"
    },
    {
      name = "event_type"
      type = "STRING"
      mode = "REQUIRED"
    },
    {
      name = "event_action"
      type = "STRING"
      mode = "REQUIRED"
    },
    {
      name = "event_severity"
      type = "STRING"
      mode = "REQUIRED"
    },
    {
      name = "event_category"
      type = "STRING"
      mode = "REPEATED"
    },
    {
      name = "source"
      type = "RECORD"
      mode = "REQUIRED"
      fields = [
        { name = "type", type = "STRING", mode = "REQUIRED" },
        { name = "name", type = "STRING", mode = "REQUIRED" },
        { name = "ip", type = "STRING", mode = "NULLABLE" },
        { name = "hostname", type = "STRING", mode = "NULLABLE" }
      ]
    },
    {
      name = "actor"
      type = "RECORD"
      mode = "NULLABLE"
      fields = [
        { name = "user", type = "STRING", mode = "NULLABLE" },
        { name = "email", type = "STRING", mode = "NULLABLE" },
        { name = "ip", type = "STRING", mode = "NULLABLE" },
        {
          name = "geo"
          type = "RECORD"
          mode = "NULLABLE"
          fields = [
            { name = "country", type = "STRING", mode = "NULLABLE" },
            { name = "city", type = "STRING", mode = "NULLABLE" }
          ]
        }
      ]
    },
    {
      name = "target"
      type = "RECORD"
      mode = "NULLABLE"
      fields = [
        { name = "type", type = "STRING", mode = "REQUIRED" },
        { name = "name", type = "STRING", mode = "NULLABLE" },
        { name = "ip", type = "STRING", mode = "NULLABLE" },
        { name = "port", type = "INTEGER", mode = "NULLABLE" }
      ]
    },
    {
      name = "outcome"
      type = "STRING"
      mode = "REQUIRED"
    },
    {
      name = "metadata"
      type = "JSON"
      mode = "NULLABLE"
    },
    {
      name = "pipeline"
      type = "RECORD"
      mode = "REQUIRED"
      fields = [
        { name = "version", type = "STRING", mode = "REQUIRED" },
        { name = "processed_at", type = "TIMESTAMP", mode = "REQUIRED" },
        { name = "enrichments_applied", type = "STRING", mode = "REPEATED" }
      ]
    }
  ])

  labels = {
    environment = var.environment
  }
}

# Tabla de alertas generadas
resource "google_bigquery_table" "alerts" {
  dataset_id = google_bigquery_dataset.events.dataset_id
  table_id   = "alerts"

  description = "Alerts generated by detection rules"

  time_partitioning {
    type  = "DAY"
    field = "triggered_at"
  }

  clustering = ["rule_id", "severity"]

  schema = jsonencode([
    {
      name = "id"
      type = "STRING"
      mode = "REQUIRED"
    },
    {
      name = "rule_id"
      type = "STRING"
      mode = "REQUIRED"
    },
    {
      name = "rule_name"
      type = "STRING"
      mode = "REQUIRED"
    },
    {
      name = "severity"
      type = "STRING"
      mode = "REQUIRED"
    },
    {
      name = "triggered_at"
      type = "TIMESTAMP"
      mode = "REQUIRED"
    },
    {
      name = "event_id"
      type = "STRING"
      mode = "REQUIRED"
    },
    {
      name = "message"
      type = "STRING"
      mode = "REQUIRED"
    }
  ])

  labels = {
    environment = var.environment
  }
}
